# Site wide configuration
title            : "CPC - Jekyll Boilerplate"
description      : "Boilerplate template for Cal Poly Corporation Jekyll projects"
locale           : "en_US"
repository       : ""
version          : ""
# Site owner

owner:
  name           : "Javier Garcia"
  email          : "javier.garcia549@gmail.com"
  twitter        : ""
  facebook       : ""
  instagram      : ""
  github-repo    : "https://github.com/javag97"
# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

include:
    - /_pages

exclude:
    - /dist/aspest
    
permalink: /:title/

# Markdown library
markdown: kramdown

# Site settings
baseurl: ""
url: ""

# Varibles
sitename: "Jekyll & Grunt"

environment: production

gems:
  - jekyll-redirect-from

# Collections

collections:
  components:
    output    : false
  colors:
    output    : false
